-- ---------------------------------------------------------------------
-- Membro_da_Equipe
-- ---------------------------------------------------------------------
CREATE TABLE Membro_da_Equipe (
    CPF              VARCHAR2(11)  PRIMARY KEY,
    Nome             VARCHAR2(100),
    Salario          NUMBER(10,2),
    Data_Nascimento  DATE,
    Data_Contratacao DATE
);

-- ---------------------------------------------------------------------
-- Tecnico
-- ---------------------------------------------------------------------
CREATE TABLE Tecnico (
    CPF           VARCHAR2(11) PRIMARY KEY,
    Especialidade VARCHAR2(60),
    CONSTRAINT fk_tecnico_membro
        FOREIGN KEY (CPF) REFERENCES Membro_da_Equipe(CPF)
);

-- ---------------------------------------------------------------------
-- Time
-- ---------------------------------------------------------------------
CREATE TABLE "Time" (
    COD      NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nome     VARCHAR2(80),
    Cidade   VARCHAR2(60),
    Endereco VARCHAR2(150),
    CPF      VARCHAR2(11)  NOT NULL UNIQUE,
    CONSTRAINT fk_time_tecnico
        FOREIGN KEY (CPF) REFERENCES Tecnico(CPF)
);

-- ---------------------------------------------------------------------
-- Rivaliza
-- ---------------------------------------------------------------------
CREATE TABLE Rivaliza (
    COD_1            NUMBER,
    COD_2            NUMBER,
    Apelido_Classico VARCHAR2(80),
    PRIMARY KEY (COD_1, COD_2),
    CONSTRAINT fk_riv_time1 FOREIGN KEY (COD_1) REFERENCES "Time"(COD),
    CONSTRAINT fk_riv_time2 FOREIGN KEY (COD_2) REFERENCES "Time"(COD),
    CONSTRAINT chk_riv_distintos CHECK (COD_1 <> COD_2)
);

-- ---------------------------------------------------------------------
-- Jogador
-- ---------------------------------------------------------------------
CREATE TABLE Jogador (
    CPF           VARCHAR2(11) PRIMARY KEY,
    Data_Entrou   DATE,
    Numero_Camisa NUMBER,
    COD           NUMBER,
    CONSTRAINT fk_jog_membro  FOREIGN KEY (CPF) REFERENCES Membro_da_Equipe(CPF),
    CONSTRAINT fk_jog_time    FOREIGN KEY (COD) REFERENCES "Time"(COD),
    CONSTRAINT uq_camisa_time UNIQUE (COD, Numero_Camisa)
);

-- ---------------------------------------------------------------------
-- Posicoes (multivalorado)
-- ---------------------------------------------------------------------
CREATE TABLE Posicoes (
    CPF     VARCHAR2(11),
    Posicao VARCHAR2(30),
    PRIMARY KEY (CPF, Posicao),
    CONSTRAINT fk_pos_jogador FOREIGN KEY (CPF) REFERENCES Jogador(CPF)
);

-- ---------------------------------------------------------------------
-- Cartao
-- ---------------------------------------------------------------------
CREATE TABLE Cartao (
    COD             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Jogos_Suspensao NUMBER
);

-- ---------------------------------------------------------------------
-- Campeonato
-- ---------------------------------------------------------------------
CREATE TABLE Campeonato (
    COD         NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Nome        VARCHAR2(100),
    Tipo        VARCHAR2(40),
    Data_Inicio DATE,
    Data_Fim    DATE
);

-- ---------------------------------------------------------------------
-- Rodada
-- ---------------------------------------------------------------------
CREATE TABLE Rodada (
    COD    NUMBER,
    Numero NUMBER,
    PRIMARY KEY (COD, Numero),
    CONSTRAINT fk_rod_camp FOREIGN KEY (COD) REFERENCES Campeonato(COD)
);

-- ---------------------------------------------------------------------
-- Partida
-- ---------------------------------------------------------------------
CREATE TABLE Partida (
    ID       NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Placar_V NUMBER,
    Placar_M NUMBER,
    Data     DATE,
    Arbitro  VARCHAR2(100),
    Publico  NUMBER,
    COD_R    NUMBER,
    Numero   NUMBER,
    COD_M    NUMBER,
    COD_V    NUMBER,
    CONSTRAINT fk_part_rodada    FOREIGN KEY (COD_R, Numero) REFERENCES Rodada(COD, Numero),
    CONSTRAINT fk_part_mandante  FOREIGN KEY (COD_M) REFERENCES "Time"(COD),
    CONSTRAINT fk_part_visitante FOREIGN KEY (COD_V) REFERENCES "Time"(COD),
    CONSTRAINT chk_part_times_distintos CHECK (COD_M <> COD_V)
);

-- ---------------------------------------------------------------------
-- Recebe
-- ---------------------------------------------------------------------
CREATE TABLE Recebe (
    CPF    VARCHAR2(11),
    COD    NUMBER,
    ID     NUMBER,
    Minuto NUMBER,
    Motivo VARCHAR2(150),
    PRIMARY KEY (CPF, COD, ID),
    CONSTRAINT fk_rec_jog     FOREIGN KEY (CPF) REFERENCES Jogador(CPF),
    CONSTRAINT fk_rec_cartao  FOREIGN KEY (COD) REFERENCES Cartao(COD),
    CONSTRAINT fk_rec_partida FOREIGN KEY (ID)  REFERENCES Partida(ID)
);

-- ---------------------------------------------------------------------
-- Empresa
-- ---------------------------------------------------------------------
CREATE TABLE Empresa (
    CNPJ VARCHAR2(14)  PRIMARY KEY,
    Nome VARCHAR2(100)
);

-- ---------------------------------------------------------------------
-- Patrocina
-- ---------------------------------------------------------------------
CREATE TABLE Patrocina (
    COD      NUMBER,
    CNPJ     VARCHAR2(14),
    DATA_PAT DATE,
    Valor    NUMBER(12,2),
    PRIMARY KEY (COD, CNPJ, DATA_PAT),
    CONSTRAINT fk_pat_camp    FOREIGN KEY (COD)  REFERENCES Campeonato(COD),
    CONSTRAINT fk_pat_empresa FOREIGN KEY (CNPJ) REFERENCES Empresa(CNPJ)
);

-- ---------------------------------------------------------------------
-- Acao_Promocional
-- ---------------------------------------------------------------------
CREATE TABLE Acao_Promocional (
    COD       NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Tipo      VARCHAR2(40),
    Data_Acao DATE,
    Descricao VARCHAR2(255),
    COD_P     NUMBER,
    CNPJ      VARCHAR2(14),
    DATA_P    DATE,
    CONSTRAINT fk_acao_patrocina
        FOREIGN KEY (COD_P, CNPJ, DATA_P) REFERENCES Patrocina(COD, CNPJ, DATA_PAT)
);

COMMIT;